// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_4Zx9pl9gv2Q8rHuOobt3KUzQ21vyGaA',
    appId: '1:400542773741:web:84c93625ec8bbb058ab7e4',
    messagingSenderId: '400542773741',
    projectId: 'productivity-app-ef29d',
    authDomain: 'productivity-app-ef29d.firebaseapp.com',
    storageBucket: 'productivity-app-ef29d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvpzL12h_Ha64t7rTl3LiBx-2CgyoEuz8',
    appId: '1:400542773741:android:e28ab3e6bb3e6f4b8ab7e4',
    messagingSenderId: '400542773741',
    projectId: 'productivity-app-ef29d',
    storageBucket: 'productivity-app-ef29d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuFZVu1hmdw82RBpTTofAGAqf1VQ3agKs',
    appId: '1:400542773741:ios:8a7d8b811dd445808ab7e4',
    messagingSenderId: '400542773741',
    projectId: 'productivity-app-ef29d',
    storageBucket: 'productivity-app-ef29d.appspot.com',
    iosClientId: '400542773741-96oh8i3ho4f6va4dm4sq39j4jilr7tc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.productivityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuFZVu1hmdw82RBpTTofAGAqf1VQ3agKs',
    appId: '1:400542773741:ios:8a7d8b811dd445808ab7e4',
    messagingSenderId: '400542773741',
    projectId: 'productivity-app-ef29d',
    storageBucket: 'productivity-app-ef29d.appspot.com',
    iosClientId: '400542773741-96oh8i3ho4f6va4dm4sq39j4jilr7tc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.productivityApp',
  );
}
